CREATE TABLE IF NOT EXISTS public.users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  varchar(255)                            NOT NULL,
    email varchar(255)                            NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  varchar(255)                            NOT NULL,
    requestor_id bigint                                  NOT NULL,
    insert_date timestamp without time zone             NOT NULL,
    CONSTRAINT requests_pk PRIMARY KEY (id),
    CONSTRAINT requests_users_fk FOREIGN KEY (requestor_id) REFERENCES public.users (id)
);

CREATE TABLE IF NOT EXISTS public.items
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name"       varchar(255)                            NOT NULL,
    description  varchar(255)                            NOT NULL,
    is_available bool                                    NOT NULL,
    owner_id     bigint                                  NOT NULL,
    request_id   bigint                                  NULL,
    CONSTRAINT items_pk PRIMARY KEY (id),
    CONSTRAINT items_users_fk FOREIGN KEY (owner_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT items_requests_fk FOREIGN KEY (request_id) REFERENCES public.requests (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public."comments"
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "text"      varchar                                 NOT NULL,
    item_id     bigint                                  NOT NULL,
    insert_date timestamp without time zone             NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT comments_pk PRIMARY KEY (id),
    CONSTRAINT comments_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES public.items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp without time zone             NOT NULL,
    end_date   timestamp without time zone             NOT NULL,
    item_id    bigint                                  NOT NULL,
    booker_id  bigint                                  NOT NULL,
    status     int                                     NOT NULL,
    CONSTRAINT booking_pk PRIMARY KEY (id),
    CONSTRAINT bookings_status_check CHECK (status between 0 and 3),
    CONSTRAINT bookings_items_fk FOREIGN KEY (item_id) REFERENCES public.items (id) ON DELETE CASCADE,
    CONSTRAINT bookings_users_fk FOREIGN KEY (booker_id) REFERENCES public.users (id) ON DELETE CASCADE
);